/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.atm;

import com.atm.config.AppConfig;
import com.atm.menu.MenuOptions;
import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;


public class App {
    public static void main(String[] args) {
        ApplicationContext context = new AnnotationConfigApplicationContext(AppConfig.class); // 1
        var menu = (MenuOptions) context.getBean("menuOptions");
        while(true)
            menu.displayMenu();
    }
}
